// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLqhxaYZFleFhPHS0yf_HuxUnxO_ZxMtg',
    appId: '1:895114349286:web:b768e9c894e2291b2b8927',
    messagingSenderId: '895114349286',
    projectId: 'bird-repeller',
    authDomain: 'bird-repeller.firebaseapp.com',
    storageBucket: 'bird-repeller.appspot.com',
    measurementId: 'G-989H5QHLFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofQ6rg1_9ikYSHPx1uI_9QcK5RkeQ1QE',
    appId: '1:895114349286:android:fe2f6df787b391192b8927',
    messagingSenderId: '895114349286',
    projectId: 'bird-repeller',
    storageBucket: 'bird-repeller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAotEkY8Srr2HJkIamrw8yMJSQLXfmFW8',
    appId: '1:895114349286:ios:b0ad2dd9ea56eda12b8927',
    messagingSenderId: '895114349286',
    projectId: 'bird-repeller',
    storageBucket: 'bird-repeller.appspot.com',
    iosBundleId: 'com.example.wildfree02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAotEkY8Srr2HJkIamrw8yMJSQLXfmFW8',
    appId: '1:895114349286:ios:bce5bf7a99976e592b8927',
    messagingSenderId: '895114349286',
    projectId: 'bird-repeller',
    storageBucket: 'bird-repeller.appspot.com',
    iosBundleId: 'com.example.wildfree02.RunnerTests',
  );
}
